---
sudo: false
language: ruby
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0"

