---
classes:
    - ruby
    - ruby::dev
    - apache
    - apache::mod::passenger

apache::mod::passenger::require:
    - Class[ruby]
    - Apt::source[passenger]

ruby::version: latest
ruby::latest_release: true
ruby::gems_version: latest

ruby::dev::ensure: latest

apt::source:
    passenger:
        location: https://oss-binaries.phusionpassenger.com/apt/passenger
        repos: main
        required_packages: apt-transport-https ca-certificates
        key: 561F9B9CAC40B2F7
        key_server: keyserver.ubuntu.com
        include_src: false

package:
    passenger-dev:
        ensure: latest
        require: Apt::source[passenger]
